### PR TITLE
JTS geometries in Place

### PR DESCRIPTION
**Pull request by tobsesHub**
# JTS geometries in Place

## context
On the LegGeometry we added methods, to get JTS LineStrings. To be consistent, it's good to add such methods in places(JTS Point, Geometry).

## Description
- This PR adds methods to get coordinates or points as JTS models from a Place object.
- also added tests for transit legs properties, which do not depend on the JTS changes.

### CODE REVIEW

**Comment by tobsesHub** [comment]
I can also change the Place record as an abstract class. I'm not sure, if that would have any advantage in this case.

**Comment by leonardehrenfried** [comment]
This is PR is fine.

If you want to invest the time it would be great if you could refactor the place to be a sealed interface with several implementations.

**Comment by leonardehrenfried** [comment]
You could also do that in a separate PR.

**Comment by tobsesHub** [comment]
> This is PR is fine.
> 
> If you want to invest the time it would be great if you could refactor the place to be a sealed interface with several implementations. Are you interested in doing that? You'd probably have to write a bit of logic into the parser to figure out what type it is.

That's a nice idea. Yes, I can do that. I would prefer, to do this in a separate PR.

**Review by leonardehrenfried — APPROVED** [review]

**Pull request merged**
